Add Param, Add hiera
voxpupuli/puppet-gluster pull request #228
Opened 2021-06-23 11:20 UTC by Kotty666

needed if we've to deploy the whole gluster server in one Run.

Pull Request (PR) description
We needed the posibility to deploy the glusterfs-server at the first run, this won't work actually. So I've added the variable to force the binary path and disables the getvar() for the first run. With this we are able to add the Peers and Volume at the first run.

Also i've removed the params.pp and moved all to hiera.

This Pull Request (PR) fixes the following issues
#182 (if param force_binary is set)

2021-06-23 18:00 UTC, smortex requested changes
Hi, thank you for this PR.  I am not a user of gluster so might not be aware of some good reasons for relying on lookup, but since I consider it to be a code smell, I was alerted by the changes :smile: 

I added in-line notes to explain the issues to be aware of with lookup and how to avoid them.  While here, I also added a few notes.  Feel free to ask for more details/discuss the suggested changes and amend/add commits.

2021-06-28 01:26 UTC, kenyon requested changes

2021-06-28 01:26 UTC, kenyon commented on .github/workflows/ci.yml
> +on: [push, pull_request]
This file is synchronized using our modulesync process, so please don't modify this file. Source file is here: https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.github/workflows/ci.yml.erb

2021-07-02 19:43 UTC, smortex commented
@Kotty666 you seem to be actively working on this and your changes do not seem ready to merge ATM, so I will close the PR for now so that we are not notified each time you push changes.

When you are done with your change, feel free to squash your commits, rebase them on top of master and re-open this PR so that we can follow-up.

Thanks!

2021-07-02 19:43 UTC, closed without merging